version: '3.8'

services:
  web:
    build:
      context: .
      args:
        DEV: ${DEV:-false}
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
      - SECRET_KEY=${SECRET_KEY:-tKVT-5zPHNhP_cPCtG0DFDratu26cMPtFIeRucLKFqDzX-ErhLdvwNfEpjQjdb2ymYA}
      - DEBUG=${DEBUG:-True}
      - MONGO_DB_NAME=${MONGO_DB_NAME:-free_mentors_db}
    depends_on:
      - mongodb
    volumes:
      - ./:/app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: